---
title: "Chapter29Answers"
format: html
editor: visual
---

```{r}
library(DT)
library(tidyverse)
library(knitr)
library(leaflet)
```

Lets create an interactive HTML Map here.

```{r}
#| label: fig-leaflet
#| fig-cap: "A map of Augustana College, Rock Island, Illinois using Leaflet"
#| fig-cap-location: top


library(leaflet)
leaflet() |>
  setView(-90.550604, 41.501591, zoom = 15) |> 
  addTiles() |>
  addMarkers(-90.550805, 41.502295, 
             popup = "The Gerber Center for Student Life")  |>
  addMarkers(-90.550073,
             41.505162,
             popup = "Evald Hall")
```

Using `DT` for interactive tables:

An example of using `DT` for an interactive table :-

```{r}
#| label: fig-DTtable
#| fig-cap: "A visually pleasing table produced using DT package"
#| fig-cap-location: top
diamonds |>
  filter(carat > 3) |>
  datatable(colnames = c("Carat", "Cut", "Color",
                         "Clarity", "Depth", "Table",
                         "Price", "X", "Y", "Z"),
            rownames = FALSE)
```
