---
title: "Chapter1&2Answers"
author: "Soban Hassan"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r  results='hide', warning=FALSE, message=FALSE}
# Prerequisites (Packages & Libraries)

lapply(c("tidyverse", "ggrepel", "palmerpenguins", "ggthemes", "ggplot2", "rlang", "forcats")
       , library, character.only = TRUE)


library(tidyverse)
library(ggrepel)
library(palmerpenguins)
library(ggthemes)
library(ggplot2)
library(rlang)
library(forcats)

# First Steps

penguins
```

```{r warning=FALSE}
##1.2.5 Exercises

#1. How many rows are in penguins? How many columns?
#There are 344 rows and 8 columns in the penguins data frame.

#2. What does the bill_depth_mm variable in the penguins data frame describe? Read the help for ?penguins to find out.
#The bill_depth_mm denotes the bill depth in millimeters.

#3. Make a scatterplot of bill_depth_mm vs. bill_length_mm. That is, make a scatterplot with bill_depth_mm on the y-axis and bill_length_mm on the x-axis. Describe the relationship between these two variables.
#There is a positive, linear, and what seems like a strong association between bill depth and bill length of penguins.

ggplot(
  data = penguins, 
  aes(x = bill_depth_mm, y = bill_length_mm)
) + 
  geom_point()

#4. What happens if you make a scatterplot of species vs. bill_depth_mm? What might be a better choice of geom?
#Species is a categorical variable and a scatterplot of a categorical variable is not that useful as it’s difficult to use it to describe the distribution of bill depth across species.

ggplot(
  data = penguins, 
  aes(x = bill_depth_mm, y = species)
) + 
  geom_point()

#5. Why does the following give an error and how would you fix it?
# No aesthetic mappings for x and y are provided and these are required aesthetics for the point geom.

#6. What does the na.rm argument do in geom_point()? What is the default value of the argument? Create a scatterplot where you successfully use this argument set to TRUE.
#Setting the na.rm argument to TRUE removes the missing values without a warning. The value for this argument is FALSE by default.

ggplot(
  data = penguins, 
  aes(x = bill_depth_mm, y = bill_length_mm)
) + 
  geom_point(na.rm = TRUE)

#7. Add the following caption to the plot you made in the previous exercise: “Data come from the palmerpenguins package.” Hint: Take a look at the documentation for labs().
#The plot from the previous exercise with caption added is provided below.

ggplot(
  data = penguins,
  aes(x = bill_depth_mm, y = bill_length_mm)
) +
  geom_point(na.rm = TRUE) +
  labs(caption = "Data come from the palmerpenguins package.")

#8. Recreate the following visualization. What aesthetic should bill_depth_mm be mapped to? And should it be mapped at the global level or at the geom level?
# The code for recreating the visualization is provided below. The bill_depth_mm variable should be mapped at the local level, only for the point geom, as it is not used for the smooth geom – the points are colored for bill depth but the smooth line is a single color.

ggplot(
  data = penguins,
  aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(aes(color = bill_depth_mm)) + 
  geom_smooth()

#9. Run this code in your head and predict what the output will look like. Then, run the code in R and check your predictions.
#I would expect the a scatterplot of body mass vs. flipper length with points and smooth lines for each species in a different color. The plot below exactly shows this as I expected.

ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g, color = island)
) +
  geom_point() +
  geom_smooth(se = FALSE)

#10. Will these two graphs look different? Why/why not?
#The two plots will look the same as in the first plot the aesthetic mappings are at the global level and passed down to both geoms, and in the second plot both geoms have the same aesthetic mappings, each defined at the local level.

ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point() +
  geom_smooth()

ggplot() +
  geom_point(
    data = penguins,
    mapping = aes(x = flipper_length_mm, y = body_mass_g)
  ) +
  geom_smooth(
    data = penguins,
    mapping = aes(x = flipper_length_mm, y = body_mass_g)
  )


##1.4.3 Exercises

#1. Make a bar plot of species of penguins, where you assign species to the y aesthetic. How is this plot different?
# This code makes the bars horizontal instead of vertical.

ggplot(penguins, aes(y = species)) + 
  geom_bar()

#2. How are the following two plots different? Which aesthetic, color or fill, is more useful for changing the color of bars?
#In the first plot, the borders of the bars are colored. In the second plot, the bars are filled in with colors. The fill aesthetic is more useful for changing the color of the bars.

ggplot(penguins, aes(x = species)) +
  geom_bar(color = "red")

ggplot(penguins, aes(x = species)) +
  geom_bar(fill = "red")

#3. What does the bins argument in geom_histogram() do?
#It determines the number of bins (bars) in a histogram.

#4. Make a histogram of the carat variable in the diamonds dataset that is available when you load the tidyverse package. Experiment with different binwidths. What binwidth reveals the most interesting patterns?
#Below are histograms with three different binwidths. I think a binwidth of 1 shows the most interesting patterns.

ggplot(diamonds, aes(x = carat)) +
  geom_histogram(binwidth = 0.01)

ggplot(diamonds, aes(x = carat)) +
  geom_histogram(binwidth = 0.10)

ggplot(diamonds, aes(x = carat)) +
  geom_histogram(binwidth = 1)

##1.5.5 Exercises

#1. The mpg data frame that is bundled with the ggplot2 package contains 234 observations collected by the US Environmental Protection Agency on 38 car models. Which variables in mpg are categorical? Which variables are numerical? (Hint: Type ?mpg to read the documentation for the dataset.) How can you see this information when you run mpg?
#manufacturer, class, fl, drv, model, and trans are all categorical variables. displ, year, cyl, cty, and hwy are all numerical variables. You can run glimpse(mpg) or ?mpg to see a list of the variables.

#2. Make a scatterplot of hwy vs. displ using the mpg data frame. Next, map a third, numerical variable to color, then size, then both color and size, then shape. How do these aesthetics behave differently for categorical vs. numerical variables?
# The difference is a numerical variable doesn’t work with shape aesthetic but a categorical variable does. Also, the color scale is different for numerical and categorical variables.

ggplot(
  mpg, 
  aes(x = hwy, y = displ, color = cty)
) + 
  geom_point()

ggplot(
  mpg, 
  aes(x = hwy, y = displ, size = cty)
) + 
  geom_point()

ggplot(
  mpg, 
  aes(x = hwy, y = displ, size = cty, color = cty)
) + 
  geom_point()

ggplot(
  mpg, 
  aes(x = hwy, y = displ, size = cty, color = cty, shape = drv)
) + 
  geom_point()

#3. In the scatterplot of hwy vs. displ, what happens if you map a third variable to linewidth?
# Since there is no line to alter the width of, nothing happens. The code runs as though that aesthetic was not specified.

ggplot(mpg, aes(x = hwy, y = displ, linewidth = cty)) + 
  geom_point()

#4. What happens if you map the same variable to multiple aesthetics?
#See below for a sample plot that maps hwy to x, yy, and color aesthetics. ggplot2 will allow you to map the same variable to multiple aesthetics, but the resulting plot is not useful.

ggplot(mpg, aes(x = hwy, y = hwy, color = hwy)) + 
  geom_point()

#5. Make a scatterplot of bill_depth_mm vs. bill_length_mm and color the points by species. What does adding coloring by species reveal about the relationship between these two variables? What about faceting by species?
#Adelies tend to have higher bill depth while Gentoo have longer bills and Chinstrap have deeper and longer bills.

ggplot(
  penguins,
  aes(x = bill_depth_mm, y = bill_length_mm, color = species)
) + 
  geom_point()

#6. Why does the following yield two separate legends? How would you fix it to combine the two legends?
#The code provided in the exercise yields two separate legends because the legend for color is renamed to "Species" but the legend for shape is not, and is named "species" by default instead. To fix it, we would need to explicitly rename the shape legend as well.

ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    color = species, shape = species
  )
) +
  geom_point() +
  labs(
    color = "Species",
    shape = "Species"
  )

#7. Create the two following stacked bar plots. Which question can you answer with the first one? Which question can you answer with the second one?
#

ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(position = "fill")
ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = "fill")

##1.6.1 Exercises

#Run the following lines of code. Which of the two plots is saved as mpg-plot.png? Why?
#The second plot is saved, because ggsave() saves the last plot you made

ggplot(mpg, aes(x = class)) +
  geom_bar()

ggplot(mpg, aes(x = cty, y = hwy)) +
  geom_point()

ggsave("mpg-plot.png")

#What do you need to change in the code above to save the plot as a PDF instead of a PNG? How could you find out what types of image files would work in ggsave()?
#You need to change the suffix of the file from png to pdf in the ggsave() call.

##2.5 Exercises

#1. Why does this code not work?
#The variable is called my_variable while the next line calls it my_varıable, with an an ı (i without a dot) in the variable name. Therefore the error is due to the mismatch in variable names.

#2. Tweak each of the following R commands so that they run correctly:
# The corrected code is provided below.

ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() +
  geom_smooth(method = "lm")

#3. Press Option + Shift + K / Alt + Shift + K. What happens? How can you get to the same place using the menus?
#Option + Shift + K / Alt + Shift + K pulls up keyboard shortcuts. Alternatively, you can use Help > Keyboard Shortcuts Help.

#4. Let’s revisit an exercise from the Section 1.6. Run the following lines of code. Which of the two plots is saved as mpg-plot.png? Why?
#The my_bar_plot object is saved because that’s what was specified in the plot argument of the ggsave() call.

my_bar_plot <- ggplot(mpg, aes(x = class)) +
  geom_bar()

my_scatter_plot <- ggplot(mpg, aes(x = cty, y = hwy)) +
  geom_point()

ggsave(filename = "mpg-plot.png", plot = my_bar_plot)
```